- name: install cron job (ansible-pull)
  cron:
    user: svc-ansible
    name: "ansible provision"
    minute: "*/10"
    job: "/usr/bin/ansible-pull -o -U https://github.com/gabor-au/ansible-pull.git > /dev/null"